/*!
    TAG V6.07.7433, smct.tag-demo.smarterclick.co.uk
    Copyright 2012-2025 intent.ly Global Ltd
*/if(typeof window.$smctResources !== 'undefined') {
    console.warn('Cannot load Tag Resources more than once...');
} else {
    window.$smctResources = function() {
        var urls = {
            tag_url : 'https://js.smct.io/t/tag-v6.07.js',
            overlays_url : 'https://js.smct.io/o/overlays-v6.07.js',
            overlays_data_url : 'https://smct.co/ov5/load/',
            smc_debug_url :  '',
            client_debug_url : 'https://js.smct.io/dp/clientDebug-v2.00.js',
            basket_backup_script : 'https://js.smct.co/v7.8.3/bb-v7.8.3.js',
            basket_backup_endpoint : 'https://ep.smct.co/bb-ep/',
            selector_tool_script : 'https://js.smct.io/s/selector-v1.00.js',
            selector_tool_endpoint : 'https://ep.smct.co/sel-ep/',
            smarter_codes_script: 'https://js.smct.co/v7.8.3/codes-v7.8.3.js',
            smarter_codes_endpoint: 'https://ep.smct.co/smcdz-ep/',
            smc_jq : 'https://js.smct.io/jq/smcJQ-v3.4.1.js',
            ls_endpoint : 'https://ls.smct.io/lse1.3.html',
            notification_app : 'https://js.smct.io/n/notifications-v1.01.js',
            notification_checker : 'https://ep.smct.co/n-c/',
            px2a_source_url: 'https://js.smct.io/e/events-1.6.0.min.js',
            px2b_endpoint_url: 'https://events.smct.co/',
            
            host : 'https://smct.co/',
            pxt_domain : 'https://ep.smct.co/',
            tag_data_url : 'https://smct.co/tm/data/',
            overlays_engage_url : 'https://ep.smct.co/ov4/e/',
            insights_url : 'https://ep.smct.co/insights/',
            url_track : 'https://ep.smct.co/ut/',
            client_debug_data : 'https://smct.co/cldbData/',
        }
            var sri = {
                tag_url : '',
                overlays_url : '',
                smc_debug_url :  '',
                client_debug_url : '',
                basket_backup_script : '',
                selector_tool_script : '',
                smarter_codes_script: '',
                smc_jq : '',
                notification_app : '',
                px2a_source_url: '',
                px2a_fingerprint_url: '',
            };
        
        var getURL = function(key, additional) {
            return urls[key];
        };

        var getSRI = function(key, additional) {
            return sri[key];
        };

        var getTagLoadedTime = function() {
            var microtime = 1760689460.3;
            return Math.round(microtime*1000);
        };

        /* Deprecated */
        var runCode = function(key, isDebug) {
            return false;
        };
        
        return {
            getURL : getURL,
            getSRI : getSRI,
            getTagLoadedTime : getTagLoadedTime,
            runCode : runCode,
            tryer: function() {
                return false;
            },
            staticFiles : 0
        };}();
    }if(typeof window.$smctData !== 'undefined') {
    console.warn('Cannot load Tag Data more than once...');
} else {
	window.$smctData = {
			a:1,
			b:1,
			h:'https://smct.co/',
		o:'eyJ2ZXJzaW9uIjoiNi4wNyIsImlkIjo1NjksIm5hbWUiOiJkZW1vLnNtYXJ0ZXJjbGljay5jby51ayIsImNzc19hbmltcyI6Ii5zbWN0LWFuaW1hdGVkey13ZWJraXQtYW5pbWF0aW9uLWR1cmF0aW9uOjFzO2FuaW1hdGlvbi1kdXJhdGlvbjoxczstd2Via2l0LWFuaW1hdGlvbi1maWxsLW1vZGU6Ym90aDthbmltYXRpb24tZmlsbC1tb2RlOmJvdGh9LnNtY3QtYW5pbWF0ZWQuc21jdC1pbmZpbml0ZXstd2Via2l0LWFuaW1hdGlvbi1pdGVyYXRpb24tY291bnQ6aW5maW5pdGU7YW5pbWF0aW9uLWl0ZXJhdGlvbi1jb3VudDppbmZpbml0ZX0uc21jdC1hbmltYXRlZC5zbWN0LWhpbmdley13ZWJraXQtYW5pbWF0aW9uLWR1cmF0aW9uOjJzO2FuaW1hdGlvbi1kdXJhdGlvbjoyc30uc21jdC1hbmltYXRlZC5zbWN0LWJvdW5jZUluLC5zbWN0LWFuaW1hdGVkLnNtY3QtYm91bmNlT3V0LC5zbWN0LWFuaW1hdGVkLnNtY3QtZmxpcE91dFgsLnNtY3QtYW5pbWF0ZWQuc21jdC1mbGlwT3V0WXstd2Via2l0LWFuaW1hdGlvbi1kdXJhdGlvbjouNzVzO2FuaW1hdGlvbi1kdXJhdGlvbjouNzVzfUAtd2Via2l0LWtleWZyYW1lcyBzbWN0LXJ1YmJlckJhbmR7MCV7LXdlYmtpdC10cmFuc2Zvcm06c2NhbGVYKDEpO3RyYW5zZm9ybTpzY2FsZVgoMSl9MzAley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlM2QoMS4yNSwuNzUsMSk7dHJhbnNmb3JtOnNjYWxlM2QoMS4yNSwuNzUsMSl9NDAley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlM2QoLjc1LDEuMjUsMSk7dHJhbnNmb3JtOnNjYWxlM2QoLjc1LDEuMjUsMSl9NTAley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlM2QoMS4xNSwuODUsMSk7dHJhbnNmb3JtOnNjYWxlM2QoMS4xNSwuODUsMSl9NjUley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlM2QoLjk1LDEuMDUsMSk7dHJhbnNmb3JtOnNjYWxlM2QoLjk1LDEuMDUsMSl9NzUley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlM2QoMS4wNSwuOTUsMSk7dHJhbnNmb3JtOnNjYWxlM2QoMS4wNSwuOTUsMSl9dG97LXdlYmtpdC10cmFuc2Zvcm06c2NhbGVYKDEpO3RyYW5zZm9ybTpzY2FsZVgoMSl9fUBrZXlmcmFtZXMgc21jdC1ydWJiZXJCYW5kezAley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlWCgxKTt0cmFuc2Zvcm06c2NhbGVYKDEpfTMwJXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKDEuMjUsLjc1LDEpO3RyYW5zZm9ybTpzY2FsZTNkKDEuMjUsLjc1LDEpfTQwJXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKC43NSwxLjI1LDEpO3RyYW5zZm9ybTpzY2FsZTNkKC43NSwxLjI1LDEpfTUwJXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKDEuMTUsLjg1LDEpO3RyYW5zZm9ybTpzY2FsZTNkKDEuMTUsLjg1LDEpfTY1JXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKC45NSwxLjA1LDEpO3RyYW5zZm9ybTpzY2FsZTNkKC45NSwxLjA1LDEpfTc1JXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKDEuMDUsLjk1LDEpO3RyYW5zZm9ybTpzY2FsZTNkKDEuMDUsLjk1LDEpfXRvey13ZWJraXQtdHJhbnNmb3JtOnNjYWxlWCgxKTt0cmFuc2Zvcm06c2NhbGVYKDEpfX0uc21jdC1ydWJiZXJCYW5key13ZWJraXQtYW5pbWF0aW9uLW5hbWU6c21jdC1ydWJiZXJCYW5kO2FuaW1hdGlvbi1uYW1lOnNtY3QtcnViYmVyQmFuZH1ALXdlYmtpdC1rZXlmcmFtZXMgc21jdC1zaGFrZXswJSx0b3std2Via2l0LXRyYW5zZm9ybTp0cmFuc2xhdGVaKDApO3RyYW5zZm9ybTp0cmFuc2xhdGVaKDApfTEwJSwzMCUsNTAlLDcwJSw5MCV7LXdlYmtpdC10cmFuc2Zvcm06dHJhbnNsYXRlM2QoLTEwcHgsMCwwKTt0cmFuc2Zvcm06dHJhbnNsYXRlM2QoLTEwcHgsMCwwKX0yMCUsNDAlLDYwJSw4MCV7LXdlYmtpdC10cmFuc2Zvcm06dHJhbnNsYXRlM2QoMTBweCwwLDApO3RyYW5zZm9ybTp0cmFuc2xhdGUzZCgxMHB4LDAsMCl9fUBrZXlmcmFtZXMgc21jdC1zaGFrZXswJSx0b3std2Via2l0LXRyYW5zZm9ybTp0cmFuc2xhdGVaKDApO3RyYW5zZm9ybTp0cmFuc2xhdGVaKDApfTEwJSwzMCUsNTAlLDcwJSw5MCV7LXdlYmtpdC10cmFuc2Zvcm06dHJhbnNsYXRlM2QoLTEwcHgsMCwwKTt0cmFuc2Zvcm06dHJhbnNsYXRlM2QoLTEwcHgsMCwwKX0yMCUsNDAlLDYwJSw4MCV7LXdlYmtpdC10cmFuc2Zvcm06dHJhbnNsYXRlM2QoMTBweCwwLDApO3RyYW5zZm9ybTp0cmFuc2xhdGUzZCgxMHB4LDAsMCl9fS5zbWN0LXNoYWtley13ZWJraXQtYW5pbWF0aW9uLW5hbWU6c21jdC1zaGFrZTthbmltYXRpb24tbmFtZTpzbWN0LXNoYWtlfUAtd2Via2l0LWtleWZyYW1lcyBzbWN0LXB1bHNlezAley13ZWJraXQtdHJhbnNmb3JtOnNjYWxlWCgxKTt0cmFuc2Zvcm06c2NhbGVYKDEpfTUwJXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZTNkKDEuMDUsMS4wNSwxLjA1KTt0cmFuc2Zvcm06c2NhbGUzZCgxLjA1LDEuMDUsMS4wNSl9dG97LXdlYmtpdC10cmFuc2Zvcm06c2NhbGVYKDEpO3RyYW5zZm9ybTpzY2FsZVgoMSl9fUBrZXlmcmFtZXMgc21jdC1wdWxzZXswJXstd2Via2l0LXRyYW5zZm9ybTpzY2FsZVgoMSk7dHJhbnNmb3JtOnNjYWxlWCgxKX01MCV7LXdlYmtpdC10cmFuc2Zvcm06c2NhbGUzZCgxLjA1LDEuMDUsMS4wNSk7dHJhbnNmb3JtOnNjYWxlM2QoMS4wNSwxLjA1LDEuMDUpfXRvey13ZWJraXQtdHJhbnNmb3JtOnNjYWxlWCgxKTt0cmFuc2Zvcm06c2NhbGVYKDEpfX0uc21jdC1wdWxzZXstd2Via2l0LWFuaW1hdGlvbi1uYW1lOnNtY3QtcHVsc2U7YW5pbWF0aW9uLW5hbWU6c21jdC1wdWxzZX1ALXdlYmtpdC1rZXlmcmFtZXMgc21jdC1mbGFzaHswJSw1MCUsdG97b3BhY2l0eToxfTI1JSw3NSV7b3BhY2l0eTowfX1Aa2V5ZnJhbWVzIHNtY3QtZmxhc2h7MCUsNTAlLHRve29wYWNpdHk6MX0yNSUsNzUle29wYWNpdHk6MH19LnNtY3QtZmxhc2h7LXdlYmtpdC1hbmltYXRpb24tbmFtZTpzbWN0LWZsYXNoO2FuaW1hdGlvbi1uYW1lOnNtY3QtZmxhc2h9IiwiY29uZmlnIjp7InRhZ1JlZnJlc2hJRCI6MzU2MzgsImpRdWVyeUZvcmNlTG9hZCI6MCwiaWdub3JlSGFzaCI6MSwiY2FzZVNlbnNpdGl2ZSI6MCwiaW5zaWdodHMiOjAsImJsb2NrSWZyYW1lIjowLCJweFRyYWNrT2ZmIjowLCJydWxlc1VUQyI6MCwiZm9yY2VPbkRlYnVnIjowLCJweEFwYyI6MSwiT3ZSZXFJbnQiOjAsIkZpcnN0Q2hhckFzY2lpRml4IjowLCJlbmNvZGVDb29raWVzIjoxLCJyZWZFeGFjdE1hdGNoIjowLCJtaWdyYXRlQ29va2llc1RvTG9jYWxTdG9yYWdlIjowLCJlbmZvcmNlU3JpIjowLCJ0aW1lb3V0IjozMDAsInNjYW5uZXJUaW1lIjozMDAsImNvb2tpZU1heEFnZURheXMiOiIiLCJvdkNvb2tpZUhpc3RvcnkiOiIiLCJzcmNfY29faW8iOiJhdXRvIiwiaW5zaWdodHNfYXV0byI6IjE1NTYxMTY2MjYiLCJsczNyZHB0eVVJRCI6MSwiZHluYW1pY0VsZW1lbnRzIjp7IkJhc2tldFZhbHVlIjp7ImFjdGl2ZSI6MSwiZXhwb3J0IjoxLCJjb29raWVTZWFyY2giOiIiLCJyZWFkQ3VzdG9tVmFyT3JGdW5jIjoiIiwic3RyaW5ncyI6IiIsInVybENvbnRhaW5zIjowLCJodG1sQ29udGFpbnMiOjAsInNlYXJjaERMT2JqZWN0IjoiIiwic2VhcmNoRExLZXkiOiIiLCJzZWxlY3RvciI6IiNjYXJ0LXRvdGFsIiwidXNlTGFzdCI6MCwiY29va2llQmFja3VwIjoxLCJ0eXBlIjoidGV4dCIsImF0dHIiOiIiLCJjdXN0b21PdmVyUmlkZSI6IiIsImZ1bmNzIjpbeyJ0eXBlIjoiZGlnaXRzIiwidmFscyI6WyIiLCIiXX1dfSwiQ29uZmlybWF0aW9uUGFnZSI6eyJhY3RpdmUiOjEsImV4cG9ydCI6MSwiY29va2llU2VhcmNoIjoiIiwicmVhZEN1c3RvbVZhck9yRnVuYyI6IiIsInN0cmluZ3MiOiJcL2NvbmZpcm1lZC5waHAiLCJ1cmxDb250YWlucyI6MSwiaHRtbENvbnRhaW5zIjowLCJzZWFyY2hETE9iamVjdCI6IiIsInNlYXJjaERMS2V5IjoiIiwic2VsZWN0b3IiOiIiLCJ1c2VMYXN0IjowLCJjb29raWVCYWNrdXAiOjAsInR5cGUiOiJ0ZXh0IiwiYXR0ciI6IiIsImN1c3RvbU92ZXJSaWRlIjoiIn0sIk9yZGVySWQiOnsiYWN0aXZlIjoxLCJleHBvcnQiOjEsImNvb2tpZVNlYXJjaCI6IiIsInJlYWRDdXN0b21WYXJPckZ1bmMiOiIiLCJzdHJpbmdzIjoiIiwidXJsQ29udGFpbnMiOjAsImh0bWxDb250YWlucyI6MCwic2VhcmNoRExPYmplY3QiOiIiLCJzZWFyY2hETEtleSI6IiIsInNlbGVjdG9yIjoiI29yZGVyLWlkIiwidXNlTGFzdCI6MCwiY29va2llQmFja3VwIjowLCJ0eXBlIjoidGV4dCIsImF0dHIiOiIiLCJjdXN0b21PdmVyUmlkZSI6IiJ9LCJPYmplY3RLZXkiOnsiYWN0aXZlIjoxLCJleHBvcnQiOjEsImNvb2tpZVNlYXJjaCI6IiIsInJlYWRDdXN0b21WYXJPckZ1bmMiOiJvYmplY3RLZXkiLCJzdHJpbmdzIjoiIiwidXJsQ29udGFpbnMiOjAsImh0bWxDb250YWlucyI6MCwic2VhcmNoRExPYmplY3QiOiIiLCJzZWFyY2hETEtleSI6IiIsInNlbGVjdG9yIjoiIiwidXNlTGFzdCI6MCwiY29va2llQmFja3VwIjowLCJ0eXBlIjoidGV4dCIsImF0dHIiOiIifSwiQ3VycmVuY3kiOnsiYWN0aXZlIjoxLCJleHBvcnQiOjEsImNvb2tpZVNlYXJjaCI6IiIsInJlYWRDdXN0b21WYXJPckZ1bmMiOiJDdXJyZW5jeSIsInN0cmluZ3MiOiIiLCJ1cmxDb250YWlucyI6MCwiaHRtbENvbnRhaW5zIjowLCJzZWFyY2hETE9iamVjdCI6IiIsInNlYXJjaERMS2V5IjoiIiwic2VsZWN0b3IiOiIiLCJ1c2VMYXN0IjowLCJjb29raWVCYWNrdXAiOjAsInR5cGUiOiJ0ZXh0IiwiYXR0ciI6IiJ9LCJCYXNrZXRDb3VudCI6eyJhY3RpdmUiOjEsImV4cG9ydCI6MSwiY29va2llU2VhcmNoIjoiIiwicmVhZEN1c3RvbVZhck9yRnVuYyI6IkJhc2tldENvdW50Iiwic3RyaW5ncyI6IiIsInVybENvbnRhaW5zIjowLCJodG1sQ29udGFpbnMiOjAsInNlYXJjaERMT2JqZWN0IjoiIiwic2VhcmNoRExLZXkiOiIiLCJzZWxlY3RvciI6IiIsInVzZUxhc3QiOjAsImNvb2tpZUJhY2t1cCI6MCwidHlwZSI6InRleHQiLCJhdHRyIjoiIn19LCJyZWZzIjp7IjM3MiI6eyJ1Ijoic21jX2JiZWlkIiwiZCI6IjIifX0sImRiIjowLCJvdmVybGF5c191cmwiOiJodHRwczpcL1wvanMuc21jdC5pb1wvb1wvb3ZlcmxheXMtdjYuMDcuanMiLCJvdmVybGF5c19kYXRhX3VybCI6Imh0dHBzOlwvXC9zbWN0LmNvXC9vdjVcL2xvYWRcLyIsIm92ZXJsYXlzX2VuZ2FnZV91cmwiOiJodHRwczpcL1wvZXAuc21jdC5jb1wvb3Y0XC9lXC8iLCJpbnNpZ2h0c191cmwiOiJodHRwczpcL1wvZXAuc21jdC5jb1wvaW5zaWdodHNcLyIsImNsaWVudF9kZWJ1Z191cmwiOiJodHRwczpcL1wvanMuc21jdC5pb1wvZHBcL2NsaWVudERlYnVnLXYyLjAwLmpzIiwiY2xpZW50X2RlYnVnX2RhdGEiOiJodHRwczpcL1wvc21jdC5jb1wvY2xkYkRhdGFcLyIsImxzX2VuZHBvaW50IjoiaHR0cHM6XC9cL2xzLnNtY3QuaW9cL2xzZTEuMy5odG1sIiwidGFnX3ByZXZpZXciOiJkZWZhdWx0Iiwid2VicHVzaF9rZXkiOiJCSlhoY3BrUHhxOXE1Ums4YTF3VnkzTVQ2Ykl6UlhnYXZqd0Y4Q2w0SXZEeGViQ1pHUEFrMkdlMTdHREVkeXVjVzBUT3FPUGt3YVBvanFCQzJyUU84bWMiLCJweHRfdmVyc2lvbiI6IjJhIiwicHh0X2lkZW50aXR5X3Bvb2xfaWQiOiJldS13ZXN0LTE6OWEyOGNiZGUtMzgzZS00YzViLWJkZGQtM2IzN2E5YTdkMWJlIn0sInNyY19jb19pbyI6ImF1dG8iLCJydWxlc0xpc3QiOlt7InJ1bGVuYW1lIjoiU2FiaW5hIEMiLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJkeW5CYXNrZXRNaW5RdHkiOiIiLCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6IjM1In0sIm1vYmlsZSI6eyJpZCI6IjM2In0sInRhYmxldCI6eyJpZCI6IjM5In19fSx7InJ1bGVuYW1lIjoiQkIgUmVmZXJyZXIgVGVzdCIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbMzcyXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOiIiLCJmaWx0ZXJHcm91cCI6IiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoyNzc0fSwibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfX19LHsicnVsZW5hbWUiOiJFbnZvbHZlIERlbW8iLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyI/ZW52b2x2ZSJdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjM3MDM3fSwibW9iaWxlIjp7ImlkIjozNzAzN30sInRhYmxldCI6eyJpZCI6MzcwMzd9fX0seyJydWxlbmFtZSI6IkVudm9sdmUgMiIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbIj9lbnZvbHZlMiJdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjM3MDczfSwibW9iaWxlIjp7ImlkIjozNzA3M30sInRhYmxldCI6eyJpZCI6MzcwNzN9fX0seyJydWxlbmFtZSI6IlJlZmVyIGEgZnJpZW5kIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiP3JlZmVyIl19LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MzY5MDF9LCJtb2JpbGUiOnsiaWQiOjM2OTAxfSwidGFibGV0Ijp7ImlkIjozNjkwMX19fSx7InJ1bGVuYW1lIjoiUmVmZXIgYSBmcmllbmQgKFNvY2lhbCkiLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyI/c29jaWFsIl19LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MzcwMTd9LCJtb2JpbGUiOnsiaWQiOjM3MDE3fSwidGFibGV0Ijp7ImlkIjozNzAxN319fSx7InJ1bGVuYW1lIjoiVGVzdGluZyBjb3B5aW5nIGFjdGl2YXRpb24iLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MzQwMzd9LCJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9fX0seyJydWxlbmFtZSI6IlBob25lIERvd24gVGVzdCIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOiIiLCJmaWx0ZXJHcm91cCI6IiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoyOTU3Mn0sIm1vYmlsZSI6eyJpZCI6Mjk1NzJ9LCJ0YWJsZXQiOnsiaWQiOjI5NTcyfX19LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiXC9jYXJ0LnBocCIsIlwvY2hlY2tvdXQucGhwIl19LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjgwMDl9LCJ0YWJsZXQiOnsiaWQiOjgwMDl9LCJkZXNrdG9wIjp7ImlkIjo4MDA4fX0sInJ1bGVuYW1lIjoiUmVtYWlsIENvbnNlbnQgT3ZlcmxheXMgKERlc2t0b3AgYW5kIE1vYmlsZSkiLCJ2aXNpdG9ycyI6ImFsbCIsInBhZ2VWaWV3cyI6IiIsInRpbWVTdGFydCI6IiIsImZpbHRlckdyb3VwIjoiIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55In0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJyZXF1ZXN0LW5vdGlmaWNhdGlvbnMiXX0sImRlbGF5IjoiIiwiZmlsdGVyIjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6Njg3NH0sInRhYmxldCI6eyJpZCI6Njg3NH0sImRlc2t0b3AiOnsiaWQiOjY4NzR9fSwicnVsZW5hbWUiOiJ2NS4xMiAtIFJlcXVlc3QgTm90aWZpY2F0aW9ucyIsInZpc2l0b3JzIjoiYWxsIiwicGFnZVZpZXdzIjoiIiwidGltZVN0YXJ0IjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJub3Rfc2V0In0seyJydWxlbmFtZSI6InY1LjEyIC0gRGlzcGxheSBvbiBOb3RpZmljYXRpb24gVGFiIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiZGlzcGxheS1vbi1ub3RpZmljYXRpb24iLCJyZXF1ZXN0LW5vdGlmaWNhdGlvbnMiXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImR5bkJhc2tldE1pblF0eSI6IiIsInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoibm90X3NldCIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjo1MCwiZmlsdGVyR3JvdXAiOiJBIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjY4NzV9LCJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9fX0seyJydWxlbmFtZSI6InY1LjEyIC0gRGlzcGxheSBvbiBOb3RpZmljYXRpb24gVGFiIChDb3B5KSIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbImRpc3BsYXktb24tbm90aWZpY2F0aW9uIiwicmVxdWVzdC1ub3RpZmljYXRpb25zIl19LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJkeW5CYXNrZXRNaW5RdHkiOiIiLCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6Im5vdF9zZXQiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6NTAsImZpbHRlckdyb3VwIjoiQiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjo2NDM4Nn0sIm1vYmlsZSI6eyJpZCI6IiJ9LCJ0YWJsZXQiOnsiaWQiOiIifX19LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsie1wvcHJvZHVjdC5waHB9Il19LCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjoyNTMxfX0sInJ1bGVuYW1lIjoiRHluYW1pYyBQcm9kdWN0IE92ZXJsYXkiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiY2xpY2stdG8tcmV2ZWFsIl19LCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjozNX19LCJydWxlbmFtZSI6IkNsaWNrIFRvIFJldmVhbCIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJpbnNlcnQtZW1haWwtdG8tcmV2ZWFsIl19LCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjozNn19LCJydWxlbmFtZSI6Ikluc2VydCBFbWFpbCBUbyBSZXZlYWwiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiYnJvY2NvbGkiXX0sImZpbHRlciI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6MH0sInRhYmxldCI6eyJpZCI6MH0sImRlc2t0b3AiOnsiaWQiOjYxNn19LCJydWxlbmFtZSI6IkJyb2Njb2xpIERlc2lnbiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJjb3VudGRvd24tdGltZXIiXX0sImZpbHRlciI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6MH0sInRhYmxldCI6eyJpZCI6MH0sImRlc2t0b3AiOnsiaWQiOjYxN319LCJydWxlbmFtZSI6IkNvdW50ZG93biBUaW1lciIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJjbGljay10by1yZWRpcmVjdCJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6Mzh9fSwicnVsZW5hbWUiOiJDbGljayB0byBSZWRpcmVjdCIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJyb3RhdGluZy1jbG9jayJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6NzM0fX0sInJ1bGVuYW1lIjoiUm90YXRpbmcgQ2xvY2siLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsibW9iaWxlLW92ZXJsYXkiXX0sImZpbHRlciI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6NDd9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjowfX0sInJ1bGVuYW1lIjoiTW9iaWxlIE92ZXJsYXkiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsidmlkZW8tYmFja2dyb3VuZCJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6NDh9fSwicnVsZW5hbWUiOiJWaWRlbyBCYWNrZ3JvdW5kIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyR3JvdXAiOiIifSx7ImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbInRlcm1zLWFuZC1jb25kaXRpb25zIl19LCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjoyMjR9fSwicnVsZW5hbWUiOiJUZXJtcyBhbmQgQ29uZGl0aW9ucyIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJhbmltYXRlZC1lbnZlbG9wZSJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6ODIwfX0sInJ1bGVuYW1lIjoiQW5pbWF0ZWQgRW52ZWxvcGUiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiZ2xvYmUtb3ZlcmxheSJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6ODI3fX0sInJ1bGVuYW1lIjoiR2xvYmUgT3ZlcmxheSIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJtb3RoZXJzLWRheS12aWRlbyJdfSwiZmlsdGVyIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6MTA0NX19LCJydWxlbmFtZSI6Ik1vdGhlcidzIERheSBWaWRlbyIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJzaWRlLXBhbmVsLXJpZ2h0Il19LCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjoyNTQwfX0sInJ1bGVuYW1lIjoiU2lkZSBQYW5lbCBSaWdodCIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJjbGljay10by1wcmludCJdfSwiZGVsYXkiOiIiLCJmaWx0ZXIiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjoyNTQzfX0sInJ1bGVuYW1lIjoiQ2xpY2sgVG8gUHJpbnQiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsiY29weXRvY2xpcGJvYXJkIl19LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjM1fSwidGFibGV0Ijp7ImlkIjozNX0sImRlc2t0b3AiOnsiaWQiOjM1fX0sInJ1bGVuYW1lIjoiQ29weSB0byBDbGlwYm9hcmQiLCJ2aXNpdG9ycyI6ImFsbCIsInBhZ2VWaWV3cyI6IiIsInRpbWVTdGFydCI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJiYWNrLWJ1dHRvbi1kaXNwbGF5Il19LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjo2ODc2fX0sInJ1bGVuYW1lIjoiVjUuMTIgLSBCYWNrIEJ1dHRvbiBEaXNwbGF5IiwidmlzaXRvcnMiOiJhbGwiLCJwYWdlVmlld3MiOiIiLCJ0aW1lU3RhcnQiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsidXJsLWNsaWNrIl19LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjo2ODc3fX0sInJ1bGVuYW1lIjoidjUuMTIgLSBVUkwgQ2xpY2siLCJ2aXNpdG9ycyI6ImFsbCIsInBhZ2VWaWV3cyI6IiIsInRpbWVTdGFydCI6IiIsImZpbHRlckdyb3VwIjoiIn0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJzdHJpcC10b3AiXX0sImRlbGF5IjoiIiwiZmlsdGVyIjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6MH0sInRhYmxldCI6eyJpZCI6MH0sImRlc2t0b3AiOnsiaWQiOjY4ODJ9fSwicnVsZW5hbWUiOiJ2NS4xMiAtIFN0cmlwIHRvcCIsInZpc2l0b3JzIjoiYWxsIiwicGFnZVZpZXdzIjoiIiwidGltZVN0YXJ0IjoiIiwiZmlsdGVyR3JvdXAiOiIifSx7ImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbInN0cmlwLWJvdHRvbSJdfSwiZGVsYXkiOiIiLCJmaWx0ZXIiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6Njg4M319LCJydWxlbmFtZSI6InY1LjEyIC0gU3RyaXAgYm90dG9tIiwidmlzaXRvcnMiOiJhbGwiLCJwYWdlVmlld3MiOiIiLCJ0aW1lU3RhcnQiOiIiLCJmaWx0ZXJHcm91cCI6IiJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsib3ZlcmxheT1oZWF0bWFwcGluZ09ubHkiXX0sImRlbGF5IjoiIiwiZmlsdGVyIjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7Im1vYmlsZSI6eyJpZCI6MTA3MTF9LCJ0YWJsZXQiOnsiaWQiOjEwNzExfSwiZGVza3RvcCI6eyJpZCI6MTA3MTF9fSwicnVsZW5hbWUiOiJIZWF0bWFwcGluZyBPbmx5IiwidmlzaXRvcnMiOiJhbGwiLCJwYWdlVmlld3MiOiIiLCJ0aW1lU3RhcnQiOiIiLCJmaWx0ZXJHcm91cCI6IiIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlsib3ZlcmxheT1wYWdlQ2xvc2VPbmx5Il19LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjEwNzEyfSwidGFibGV0Ijp7ImlkIjoxMDcxMn0sImRlc2t0b3AiOnsiaWQiOjEwNzEyfX0sInJ1bGVuYW1lIjoiUGFnZSBDbG9zZSBPbmx5IiwidmlzaXRvcnMiOiJhbGwiLCJwYWdlVmlld3MiOiIiLCJ0aW1lU3RhcnQiOiIiLCJmaWx0ZXJHcm91cCI6IiIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSJ9LHsibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZGVsYXkiOiIiLCJmaWx0ZXIiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfSwiZGVza3RvcCI6eyJpZCI6MTk0NDF9fSwicnVsZW5hbWUiOiJDYXJwaG9uZSBXYXJlaG91c2UgLSBERU1PIFBBR0UiLCJ2aXNpdG9ycyI6ImFsbCIsInBhZ2VWaWV3cyI6IiIsInRpbWVTdGFydCI6IiIsImZpbHRlckdyb3VwIjoiIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55In0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJkZWxheSI6IiIsImZpbHRlciI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJtb2JpbGUiOnsiaWQiOjB9LCJ0YWJsZXQiOnsiaWQiOjB9LCJkZXNrdG9wIjp7ImlkIjoxOTQzOH19LCJydWxlbmFtZSI6IkJhbmdnb29kIFNsb3RzIC0gREVNTyBQQUdFIiwidmlzaXRvcnMiOiJhbGwiLCJwYWdlVmlld3MiOiIiLCJ0aW1lU3RhcnQiOiIiLCJmaWx0ZXJHcm91cCI6IiIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSJ9LHsicnVsZW5hbWUiOiJCYXNrZXQgYmFsbCBnYW1lIC0gREVNTyBQQUdFIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjI5Mjc5fSwibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfX19LHsicnVsZW5hbWUiOiJTaG9vdCBFbSBVcCBHYW1lIC0gREVNTyBQQUdFIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjMwOTU1fSwibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfX19LHsicnVsZW5hbWUiOiJUZXN0aW5nIGNvcHlpbmcgYWN0aXZhdGlvbiIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOiIiLCJmaWx0ZXJHcm91cCI6IiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjozNDAzN30sIm1vYmlsZSI6eyJpZCI6MH0sInRhYmxldCI6eyJpZCI6MH19fSx7InJ1bGVuYW1lIjoiR2xvc3N5Ym94IiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjYwMjc4fSwibW9iaWxlIjp7ImlkIjowfSwidGFibGV0Ijp7ImlkIjowfX19LHsicnVsZW5hbWUiOiJ0ZXN0IG92ZXJsYXkgZm9yIGR5bmFtaWMgYmFza2V0IiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZHluQmFza2V0TWluUXR5IjoxLCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImR5bkJhc2tldFJlcXVpcmVkIjoib24iLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjg5NTI4fSwibW9iaWxlIjp7ImlkIjo4OTUyOH0sInRhYmxldCI6eyJpZCI6ODk1Mjh9fX0seyJydWxlbmFtZSI6IkVFIERlbW8iLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJkeW5CYXNrZXRNaW5RdHkiOiIiLCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6IiJ9LCJtb2JpbGUiOnsiaWQiOjkzMDMzfSwidGFibGV0Ijp7ImlkIjoiIn19fSx7InJ1bGVuYW1lIjoiVHJpbSBTcGFjZXMgVGVzdCBSdWxlIC0gU2FiaW5hIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZHluQmFza2V0TWluUXR5IjoiIiwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkeW5CYXNrZXRSZXF1aXJlZCI6Im9mZiIsInJlY29tbWluZGVyUmVxdWlyZWQiOiJvZmYiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjM5fSwibW9iaWxlIjp7ImlkIjoiIn0sInRhYmxldCI6eyJpZCI6IiJ9fX0seyJydWxlbmFtZSI6IlBob25lIERvd24gVGVzdCAoQ29weSkiLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MTA3Mjc0fSwibW9iaWxlIjp7ImlkIjoxMDcyNzV9LCJ0YWJsZXQiOnsiaWQiOjEwNzI3Nn19fSx7InJ1bGVuYW1lIjoiU2FiaW5hIEJCQkJCQiIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOjk1LCJmaWx0ZXJHcm91cCI6IlNhYmluYSBCQkJCQkIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6IjQ3In0sIm1vYmlsZSI6eyJpZCI6IjQ3In0sInRhYmxldCI6eyJpZCI6IjIyNCJ9fX0seyJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WyJyb3RhdGluZy1jbG9jayJdfSwiZmlsdGVyIjo5NSwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6IjM2In0sIm1vYmlsZSI6eyJpZCI6IjM5In0sInRhYmxldCI6eyJpZCI6IjQ3In19LCJydWxlbmFtZSI6IlJvdGF0aW5nIENsb2NrIChDb3B5KSIsInBhZ2VWaWV3cyI6IiIsImZpbHRlckdyb3VwIjoiUm90YXRpbmcgQ2xvY2sgKENvcHkpIn0seyJydWxlbmFtZSI6IkluY3JlbWVudGFsaXR5IFRlc3QgKEdyb3VwIEIpIC0gU2FiaW5hIEJCQkJCQiIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOjUsImZpbHRlckdyb3VwIjoiU2FiaW5hIEJCQkJCQiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoiMTA3NzU5In0sInRhYmxldCI6eyJpZCI6IjEwNzc2MSJ9LCJtb2JpbGUiOnsiaWQiOiIxMDc3NTkifX19LHsicnVsZW5hbWUiOiJTYWJpbmEgQyAoQ29weSkiLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJkeW5CYXNrZXRNaW5RdHkiOiIiLCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjoiIiwiZmlsdGVyR3JvdXAiOiIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MTA3NzcyfSwibW9iaWxlIjp7ImlkIjoxMDc3NzF9LCJ0YWJsZXQiOnsiaWQiOjEwNzc3M319fSx7InJ1bGVuYW1lIjoiQkIgUmVmZXJyZXIgVGVzdCAoQ29weSkiLCJ1cmxzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJyZWZzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6WzM3Ml19LCJsb2NzIjp7ImJsYWNrbGlzdCI6W10sIndoaXRlbGlzdCI6W119LCJ2aXNpdG9ycyI6ImFsbCIsIm5vdGlmaWNhdGlvbnNBY2NlcHRlZCI6ImFueSIsImRlbGF5IjoiIiwicGFnZVZpZXdzIjoiIiwiZmlsdGVyIjo5NSwiZmlsdGVyR3JvdXAiOiJCQiBSZWZlcnJlciBUZXN0IChDb3B5KSIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoiMzkifSwibW9iaWxlIjp7ImlkIjoiNDcifSwidGFibGV0Ijp7ImlkIjoiNDcifX19LHsicnVsZW5hbWUiOiJJbmNyZW1lbnRhbGl0eSBUZXN0IChHcm91cCBCKSAtIEJCIFJlZmVycmVyIFRlc3QgKENvcHkpIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOlszNzJdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6NSwiZmlsdGVyR3JvdXAiOiJCQiBSZWZlcnJlciBUZXN0IChDb3B5KSIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoiMTA3NzY4In0sIm1vYmlsZSI6eyJpZCI6IjEwNzc1OSJ9LCJ0YWJsZXQiOnsiaWQiOiIxMDc3NTkifX19LHsicnVsZW5hbWUiOiJUZXN0IiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZHluQmFza2V0TWluUXR5IjoiIiwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkeW5CYXNrZXRSZXF1aXJlZCI6Im9mZiIsInJlY29tbWluZGVyUmVxdWlyZWQiOiJvZmYiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjQ4fSwibW9iaWxlIjp7ImlkIjo2MTd9LCJ0YWJsZXQiOnsiaWQiOjQ3fX19LHsicnVsZW5hbWUiOiJUZXN0IChDb3B5KSIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImR5bkJhc2tldE1pblF0eSI6IiIsInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZHluQmFza2V0UmVxdWlyZWQiOiJvZmYiLCJyZWNvbW1pbmRlclJlcXVpcmVkIjoib2ZmIiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOiIiLCJmaWx0ZXJHcm91cCI6IiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoiMzYifSwibW9iaWxlIjp7ImlkIjoiNDcifSwidGFibGV0Ijp7ImlkIjpudWxsfX19LHsicnVsZW5hbWUiOiJTYWJpbmEgQkJCQkJCIChDb3B5KSIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOjk1LCJmaWx0ZXJHcm91cCI6IlNhYmluYSBCQkJCQkIiLCJ0aW1lU3RhcnQiOiIiLCJ0aW1lRW5kIjoiIiwib3ZlcmxheXMiOnsiZGVza3RvcCI6eyJpZCI6MTQzMzMwfSwibW9iaWxlIjp7ImlkIjoxNDMzMzF9LCJ0YWJsZXQiOnsiaWQiOjE0MzMzMn19fSx7InJ1bGVuYW1lIjoiVEVTVCBOaW5qYSBLaXRjaGVuIFJ1bGUgVmFyaWFudCBBIiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZHluQmFza2V0TWluUXR5IjoiIiwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkeW5CYXNrZXRSZXF1aXJlZCI6Im9mZiIsInJlY29tbWluZGVyUmVxdWlyZWQiOiJvZmYiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjE2ODg0MX0sIm1vYmlsZSI6eyJpZCI6MTY4ODQzfSwidGFibGV0Ijp7ImlkIjoxNjg4NDR9fX0seyJydWxlbmFtZSI6IlRFU1QgTmluamEgS2l0Y2hlbiBSdWxlIFZhcmlhbnQgQiIsInVybHMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sInJlZnMiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImxvY3MiOnsiYmxhY2tsaXN0IjpbXSwid2hpdGVsaXN0IjpbXX0sImR5bkJhc2tldE1pblF0eSI6IiIsInZpc2l0b3JzIjoiYWxsIiwibm90aWZpY2F0aW9uc0FjY2VwdGVkIjoiYW55IiwiZHluQmFza2V0UmVxdWlyZWQiOiJvZmYiLCJyZWNvbW1pbmRlclJlcXVpcmVkIjoib2ZmIiwiZGVsYXkiOiIiLCJwYWdlVmlld3MiOiIiLCJmaWx0ZXIiOiIiLCJmaWx0ZXJHcm91cCI6IiIsInRpbWVTdGFydCI6IiIsInRpbWVFbmQiOiIiLCJvdmVybGF5cyI6eyJkZXNrdG9wIjp7ImlkIjoxNjg4NDJ9LCJtb2JpbGUiOnsiaWQiOjE2ODg0Nn0sInRhYmxldCI6eyJpZCI6MTY4ODQ1fX19LHsicnVsZW5hbWUiOiJVbnN1YnNjcmliZSBCQiBUZXN0IiwidXJscyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwicmVmcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwibG9jcyI6eyJibGFja2xpc3QiOltdLCJ3aGl0ZWxpc3QiOltdfSwiZHluQmFza2V0TWluUXR5IjoiIiwiZHluYW1pY0VsZW1lbnRSdWxlcyI6eyJCYXNrZXRWYWx1ZSI6eyJpczEiOiI+PSIsInZhbDEiOiIxIiwiYW5kT3IiOiIiLCJpczIiOiI+IiwidmFsMiI6IiJ9fSwidmlzaXRvcnMiOiJhbGwiLCJub3RpZmljYXRpb25zQWNjZXB0ZWQiOiJhbnkiLCJkeW5CYXNrZXRSZXF1aXJlZCI6Im9mZiIsInJlY29tbWluZGVyUmVxdWlyZWQiOiJvZmYiLCJkZWxheSI6IiIsInBhZ2VWaWV3cyI6IiIsImZpbHRlciI6IiIsImZpbHRlckdyb3VwIjoiIiwidGltZVN0YXJ0IjoiIiwidGltZUVuZCI6IiIsIm92ZXJsYXlzIjp7ImRlc2t0b3AiOnsiaWQiOjE3NDg1M30sIm1vYmlsZSI6eyJpZCI6IiJ9LCJ0YWJsZXQiOnsiaWQiOiIifX19XSwicGx1Z2lucyI6eyJhdXRvSW5zZXJ0Ijp7InVybCI6ImNhcnQucGhwIiwiaW5wdXQiOiIjcHJvbW9jb2RlIiwiaG9sZGVyIjoiIiwiaG9sZGVyRGlzcGxheSI6ImJsb2NrIiwiZWxtQW5pbWF0ZSI6IiIsImVsbUFuaW1hdGVDbGFzcyI6InJ1YmJlckJhbmQiLCJzZWNzRGlzcCI6MiwidGltZW91dCI6NTAwfSwidHJhY2tpbmciOnsiQUJvbiI6MCwiY29uZmlybVBhZ2UiOiJDb25maXJtYXRpb25QYWdlIiwib3JkZXJWYWx1ZSI6IkJhc2tldFZhbHVlIiwib3JkZXJJRCI6Ik9yZGVySWQiLCJjdXJyZW5jeSI6IiIsIm9yZGVyQ291bnQiOiIiLCJweDEiOiIiLCJweDFMb2FkIjoiaW1nIiwiZWgiOjB9LCJiYXNrZXRCYWNrdXAiOnsiaWQiOiI1NSJ9LCJzbWFydGVyQ29kZXMiOnsiaWQiOiIxNTIifSwic2NfdHJhY2tpbmciOnsiY29uZmlybVBhZ2UiOiJDb25maXJtYXRpb25QYWdlIiwib3JkZXJWYWx1ZSI6IkJhc2tldFZhbHVlIiwib3JkZXJJRCI6IiIsImN1cnJlbmN5IjoiQ3VycmVuY3kiLCJvcmRlckNvdW50IjoiQmFza2V0Q291bnQifSwibm90aWZpY2F0aW9ucyI6eyJzZXJ2aWNlV29ya2VyIjoiXC9hc3NldHNcL2pzXC9zZXJ2aWNlLXdvcmtlci5qcyJ9LCJzb3VyY2VzIjp7InVybFNvdXJjZSI6MSwiaHR0cFJlZmVycmVyIjoxfSwicmVjb21taW5kZXIiOnsiaXRlbVNrdSI6IkNvbmZpcm1hdGlvblBhZ2UiLCJpdGVtUHJpY2UiOiIiLCJpdGVtU2FsZVByaWNlIjoiQ29uZmlybWF0aW9uUGFnZSIsIml0ZW1JbWFnZSI6IiIsIml0ZW1OYW1lIjoiT3JkZXJJZCIsIml0ZW1MaW5rIjoiIn19LCJ1c2VMb2MiOiJjb3VudHJ5IiwiaXAiOiIyMDkuOTMuMTk5LjExMyIsImlwYiI6ZmFsc2UsImRldmljZSI6ZmFsc2UsInQiOjAuMDAyMTA3LCJsb2NTaWciOiIwZjViZmI5ODMzYzEzZGM0ODFmNzJhZjAwMGRkMmE2YSJ9'
	};
}

(function(w, d) {
	var src_co_io = 'auto';
	var tld = '';

	if(src_co_io === 'co' || src_co_io === 'io') {
		tld = src_co_io;
		sessionStorage.setItem('smc_cdn_source', tld);
	} else {
		tld  = sessionStorage.getItem('smc_cdn_source');
	}

	var cspCheck = function(cb) {
		if(tld !== null) {
			cb();
		} else {
			tld = 'io';
			var ioTest = new XMLHttpRequest();
			ioTest.open('HEAD', 'https://js.smct.' + tld + '/csp/csp.js', true);
			ioTest.send();
			ioTest.onerror = function() {
				tld = 'co'
				var coTest = new XMLHttpRequest();
				coTest.open('HEAD', 'https://js.smct.' + tld + '/csp/csp.js', true);
				coTest.send();
				coTest.onerror = function() {
					tld = 'co';
					cb();
				}
				coTest.onload = function() {
					tld = 'co';
					sessionStorage.setItem('smc_cdn_source', tld);
					cb();
				}
			}
			ioTest.onload = function() {
				tld = 'io';
				sessionStorage.setItem('smc_cdn_source', tld);
				cb();
			}
		}
	}

	var addJS = function(scriptUrl, callback) {
        var url = window.$smctResources.getURL(scriptUrl);
        var sriValue = window.$smctResources.getSRI(scriptUrl);
			if(url.indexOf('://l.smct') === -1 && url.indexOf('://dev.smct') === -1 && tld !== undefined) {
				url = url.replace(/smct.(c|i)o/i, 'smct.' + tld);
			}
		var h = d.getElementsByTagName("head")[0],
			j = d.createElement('script');
		j.type = 'text/javascript';
		j.src = url;
		j.charset = 'utf-8';
		h.appendChild(j);
		j.onload = function() {
			if(callback) {
				callback();
			}
		};
	}

	try{
		cspCheck(function cspChecker() {
			addJS('tag_url', function addingJS() {
				window.$smcCallCustomScripts = function() {
					$smcT5.CustomScripts = {};
					try {
						window.intentlyOverlayEvents = window.intentlyOverlayEvents || [];

function getVariant(name) {
	if (name.includes('Variant: ')) return name.split('Variant: ')[1];

	const ruleName = JSON.parse(atob($smctData.o)).rulesList.find((rule) => {
		const ids = Object.entries(rule.overlays).map(([key, val]) => {
			return val.id;
		});
		if (ids.includes($smcO5.vars.oid)) return true;
	}).rulename;

	if (ruleName.includes('Variant: ')) return ruleName.split('Variant: ')[1];

	return null;
}

(function () {
	const eventNames = [
		'smc_overlay_loaded',
		'smc_overlay_shown',
		'smc_overlay_engaged',
		'smc_overlay_closed'
	];

	eventNames.forEach(eventName => {
		document.addEventListener(eventName, function (e) {
			const eventRecord = {
				type: eventName.replace('smc_overlay_', ''),
				timestamp: Date.now(),
				id: $smcO5.vars.oid,
				device: $smcT5.tagHelpers.get('device').device,
				name: $smcO5.vars.name,
				variant: getVariant($smcO5.vars.name),
			};

			window.intentlyOverlayEvents.push(eventRecord);

			const customEvent = new CustomEvent('intently_overlay_event', {
				detail: eventRecord
			});

			document.dispatchEvent(customEvent);
		});
	});
})();


$smcT5.CustomScripts.TagCode = function(){
    
    const promoEl = document.querySelector('#promocode');
    const promoButton = document.querySelector('.form-group .input-group button');
    if (promoEl && promoButton) {
        promoEl.addEventListener('keydown', function(e) {
            updateStuff()
        });
        promoButton.addEventListener('click', function(){
            updateStuff()
        })
    }
    
    function updateStuff() {
        if (event.key !== 'Enter' || event.keyCode !== 13) return;
        let messageEl = document.querySelector('#code-input-message');
        let discountEl = document.querySelector('#discount-amount');
        if (!messageEl) {
            const parent = document.querySelector('.form-group .input-group:has(button)');
            messageEl = document.createElement('div');
            messageEl.id = 'code-input-message';
            discountEl = document.createElement('div');
            discountEl.id = 'discount-amount';
            parent.insertAdjacentElement('afterend', discountEl);
            parent.insertAdjacentElement('afterend', messageEl);
        }
        if (promoEl.value === "hello" || promoEl.value === "20off") {
            messageEl.innerText = 'voucher applied!';
            messageEl.style.color = 'green';
            document.querySelectorAll('#cart-total').forEach((el) => el.querySelector('span').innerText = Math.floor(Number(el.querySelector('span').innerText.replace(",","")) / 2))
            discountEl.innerText = '£' + Math.round(Number(document.querySelector('#cart-total span').innerText.replace(",","")) / 2).toFixed(2); 
        } else {
            messageEl.innerText = 'voucher invalid!';
            messageEl.style.color = 'red';
            discountEl.innerText = '£0.00'
        }
    }

    Notification.requestPermission();
    /**
     * Joe 2019-10-30 - added a temporary log that records device info for each user
    */
    //var isDebug = typeof window.$smcDebugger === 'undefined' ? 0 : 1;
    /*if( $smcT5.CookieManager.read('smc_device_info_collected') === null ){

        var postObj = {
            tag_index : $smcT5.tagHelpers.get('id'),
            tag_device_id : $smcT5.tagHelpers.get('device').id,
            tag_device_type : $smcT5.tagHelpers.get('device').device,
            match_media_pointer_fine : matchMedia('(pointer:fine)').matches,
            ontouchstart_in_window : ('ontouchstart' in window) === true ? 1 : 0, 
            navigator_maxTouchPoints : navigator.maxTouchPoints,
            inner_width : window.innerWidth,
            inner_height : window.innerHeight,
            outer_width : window.outerWidth,
            outer_height : window.outerHeight,
            screen_width : screen.width,
            screen_height : screen.height,
            country_code : $smcT5.tagHelpers.get('loc').cc,
        }
        $smcT5.tagHelpers.ajax.post('https://admin.smct.co/utilities/insights/device_logs.php', postObj, function( callback ){
            console.log(callback);
            $smcT5.CookieManager.create('smc_device_info_collected',true, 60 * 24 * 7);//Don;t do this again for user for 7 days
        })
    }*/
    
    (function gyro() {
        var isDebug = typeof window.$smcDebugger === 'undefined' ? 0 : 1;
        
        let gyroscope = new Gyroscope({frequency: 60});

        gyroscope.addEventListener('reading', e => {
            $('.animation-delay-11').text(gyroscope.x);
            $('.animation-delay-13').text(gyroscope.y);
            $('.animation-delay-15').text(gyroscope.z);
        });
        
        gyroscope.start();
    })();
}

$smcT5.CustomScripts.GhostOverlays = function ghostOverlays(){
    // INFO: This engagement data will not be collected in our system.
    $smcO5.funcs.overlayRemove();
}



/*
 * K.O - 2019/11/08 - Claim Voucher function
 */
$smcT5.CustomScripts.ClaimVoucher = function claimvc(pool_id, vc_selector, non_dynamic, force_pull) {
    (function($){
        var DBW = $smcT5.tagHelpers.DBW;
        var DBC = $smcT5.tagHelpers.DBC;
        var CM = $smcT5.CookieManager;
        if(!window.$smcO5 && $){ // Requires jQuery
            DBW('Dynamic Codes: This function only works when an overlay is loaded.');
            return;
        }
        var RM = $smcO5.funcs.overlayRemove;
        vc_selector = vc_selector ? vc_selector : "smc-code";
        non_dynamic = non_dynamic ? non_dynamic : false;
        force_pull = force_pull ? force_pull : false;
        
        var cookieName = 'smc_dc_'+pool_id; // Changing this should reset all saved codes and overwrite them with new ones.
        var cookieLength = 60*60*24*31; // Save cookie for 31 days.
        var claim_endpoint = 'https://dc.smct.co/v2/claim?pool_id='+pool_id;
        
        if(force_pull || !CM.exists(cookieName)){
            // Pulling new code
            $.get(claim_endpoint).done(function claim(data){
                if(data.error){ // ERROR
                    DBW('Dynamic Codes: '+data.message);
                    RM();
                    return;
                }
                if(data.code){ // SUCCESS
                    DBC('Dynamic Codes: Code retrieved from server');
                    checkAndApply(data);
                }
                // Non existing pools
                if(data.code === "" && !data.dynamic){ // ERROR
                    DBC('Dynamic Codes: Non existing pool. Closing the overlay.');
                    RM();
                }
            });
        } else {
            try{
                var cookie = CM.read(cookieName);
                var dat = JSON.parse(atob(cookie));
                DBC('Dynamic Codes: Code retrieved from cookie');
                checkAndApply(dat, false);  
            }catch(e){
                DBW('Dynamic Codes: Could not decode cookie. Closing the overlay...');
                RM();
            }
        }
        // Code check and applying
        function checkAndApply(data, save_cookie){
            save_cookie = save_cookie===false ? save_cookie : true; // Default true
            if(!non_dynamic && !data.dynamic){
                DBW('Dynamic Codes: NON-Dynamic code present, closing the overlay.');
                RM();
                return;
            }
            // Setting up the code
            $smcO5.vars.vc = data.code;
            $(vc_selector).text(data.code);
            $('smc-cp').attr('data-clipboard-text', data.code);
            // Replace smc_vc cookie
            var smc_vc = JSON.parse($smcT5.CookieManager.read('smc_vc'))
            if(smc_vc){
                smc_vc.v = btoa(data.code);
                $smcT5.CookieManager.create('smc_vc', JSON.stringify(smc_vc), 0);
            }
            // Debug
            DBC('Dynamic Codes: Voucher code applied to the overlay.');
            // Saving the code for future use.
            if(save_cookie){
                var dat = btoa(JSON.stringify(data));
                CM.create(cookieName, dat, cookieLength);
                DBC('Dynamic Codes: Code has been saved to a cookie.');
            }
        }
    })($ || jQuery);
}

/*
 * K.O - 2019/11/08 - Check remaining vouchers.
 */
$smcT5.CustomScripts.RemainingVoucher = function remvc(pool_id, buffer) {
    buffer = buffer ? buffer : 100;
    var rem_endpoint = 'https://dc.smct.co/v2/remaining?pool_id='+pool_id;
    var displayOverlay = false;
    var DBC = $smcT5.tagHelpers.DBC;
    $.get(rem_endpoint).done(function claim(data){
        if(
            data && 
            data.approximateRemaining &&
            data.approximateRemaining > buffer
        ) displayOverlay = true;
        DBC('Remaining Voucher Updated "'+pool_id+'" to ' + displayOverlay);
        // Updating a global object
        if(!displayOverlay){ // Only update if false. Otherwise display as normal
            $smcT5.CustomScripts[pool_id] = displayOverlay;
        }
    });
}

//Testing the Dynamic Basket Plugin spams the console ticket (ADA-446) - Sabina Colaco
$smcT5.CustomScripts.objectKey = () => {
    return {
        name: 'John',
        age: 44
    };
}

$smcT5.CustomScripts.Currency = Math.floor(Math.random() * 10)%2 === 0 ? 'GBP': 'USD';
(()=>{
    const lol = Math.round(Math.random() * 10);
    $smcT5.CustomScripts.BasketCount = function(){
        return lol;
    }
})();

const addEvent = $smcT5.tagHelpers.basket.safeListener(
  "click",
  "smc-listener-added",
  () => {
    const addToCartElements = Array.from(
      document.querySelectorAll(".add-to-cart"),
    );
    return addToCartElements;
  },
  (event, target) => {
    const container = target.closest(".ec-box");
    const image = container?.querySelector("img")?.src;
    const title = container?.querySelector(".ec-box-header a")?.innerText;
    const price = container?.querySelector(
      ".ec-box-footer span.label",
    )?.innerText;
    return [{ image, title, price, quantity: 1 }];
  },
);

const syncBasket = () => {
  const products = Array.from(document.querySelectorAll("table#cart tbody tr"));
  if (products.length > 0) {
    return products.map((prod) => {
      const image = prod.querySelector(".image img")?.src;
      const title = prod.querySelector(".name a")?.innerText;
      const price = prod
        .querySelector(".price small")
        ?.innerText.split(": ")[1];
      const quantity = prod.querySelector(".qty input")?.value;
      return { image, title, price, quantity };
    });
  }
  return undefined;
};

setInterval(() => {
  $smcT5.tagHelpers.basket.shadowBasket({ addEvent, syncBasket });
}, 400);
					} catch(e) {
						console.error("CustomScripts Error: ", e);
					}
				}
			});
		});
	} catch(e) {
		console.log(e);
	}
}(window, document));

